name: DevOpsBasicTest-SecondAction

on:
  push:
    branches:
      - main

jobs:
  myTest:
    runs-on: windows-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello, World! from myTest job"

  myDeploy:
    runs-on: windows-latest
    needs: [myTest]
    steps:
      - name: Print Hello Message
        run: echo "Hello, World! from myDeploy job"
