name: DevOpsBasicTest-SecondAction
env:
  APPLICATION_NAME : "MyApp"
  DEPLOY_PACKAGE_NAME : "app-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  myTest:
    runs-on: windows-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello, World! from myTest job"

      - name: Execute few commands
        run: |
          echo "Hello Message 1"
          echo "Hello Message 2"
          echo "Application name ${{ env.APPLICATION_NAME }}"

      - name: List current folder
        run: ls

      - name: Git Clone my repo
        uses: actions/checkout@v1

  myDeploy:
    runs-on: ubuntu-latest
    #needs: [myTest]

    steps:
      - name: Print Hello Message
        run: echo "Hello, World! from myDeploy job"

      - name: Print Deployment Message
        run: echo "Deploy Package Name is ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Let's test some Packages if they are here 1
        run: aws --version

      - name: Let's test some Packages if they are here 2
        run: zip