name: DevOpsBasicTest-FirstAction

on:
  push:
    branches:
      - main

jobs:
  myTest:
    runs-on: windows-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello, World! from myTest job"
